[project]
name = "restaurant-core"
version = "0.1.0"
description = "For CRUD & booking logic"
readme = "README.md"
authors = [
    { name = "DaniaHamad" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.1",
    "psycopg2>=2.9.11",
    "sqlalchemy>=2.0.44",
]

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"
